# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Dataset": "tfrecord.ipynb",
         "get_y": "model.ipynb",
         "location_to_one_hot": "model.ipynb",
         "get_x": "model.ipynb",
         "ImageModel": "model.ipynb",
         "MyModel": "model.ipynb",
         "create_compiled_model": "model.ipynb",
         "load_modis": "model.modis.ipynb",
         "grid_metadata": "tfrecord.ipynb",
         "get_grid_data": "tfrecord.ipynb",
         "satellite_metadata": "tfrecord.ipynb",
         "get_satellite_meta": "tfrecord.ipynb",
         "fetch_subset": "tfrecord.ipynb",
         "maiac_subset_names": "tfrecord.ipynb",
         "maiac_subset_indices": "tfrecord.ipynb",
         "image_feature": "tfrecord.ipynb",
         "float_feature": "tfrecord.ipynb",
         "string_feature": "tfrecord.ipynb",
         "label_to_example": "tfrecord.ipynb",
         "series_to_locations": "tfrecord.ipynb",
         "series_to_subset_infos": "tfrecord.ipynb",
         "row_to_label": "tfrecord.ipynb",
         "create_tfrecord": "tfrecord.ipynb",
         "load_tfrecord": "tfrecord.ipynb"}

modules = ["model/__init__.py",
           "model/modis.py",
           "data/tfrecord.py"]

doc_url = "https://zehua-chen.github.io/coms4995-deep-competition/coms4995-deep-competition/"

git_url = "https://github.com/Zehua-Chen/coms4995-deep-competition"

def custom_doc_links(name): return None
