# AUTOGENERATED! DO NOT EDIT! File to edit: model.modis.ipynb (unless otherwise specified).

__all__ = ['load_modis']

# Cell
from os import path
import subprocess
import airathon.paths as paths
from osgeo import gdal

# Cell
def load_modis(year: str, granule_id: str, split: str) -> gdal.Dataset:
    """Load a MODIS, aka. MAIAC file

    Args:
        granule_id (str): _description_

    Returns:
        gdal.Dataset: _description_
    """
    # s3 = boto3.client("s3")
    # s3.download_file()
    filepath = path.join(paths.dataset(), split, "maiac", year, granule_id)

    if not path.exists(filepath):
        raise FileNotFoundError(filepath)

    modis = gdal.Open(filepath)

    return modis